[tox]
requires =
    tox>=4.51.1
    tox-uv
env_list =
    lint,
    typing-{mypy,pyright,ty,pyrefly},
    3.1{1-5}-{vanilla,pool,sqlalchemy,sqlalchemy-asyncio}-tests,
    coverage-{combine,report},
    docs-doctests


[pkgenv]
pass_env = SETUPTOOLS_SCM_PRETEND_VERSION


[testenv]
runner = uv-venv-runner
package = wheel
wheel_build_env = .pkg
dependency_groups = tests
extras =
    prometheus
    sentry
    pool: pool
    sqlalchemy: sqlalchemy
    asyncio: sqlalchemy-asyncio
commands =
    vanilla: coverage run -m pytest
    sqlalchemy: coverage run -m pytest tests/test_sqlalchemy.py
    pool: coverage run -m pytest tests/test_psycopg_pool.py


[testenv:coverage-combine]
base_python_file = .python-version
depends = *-tests
skip_install = true
deps = coverage
commands = coverage combine

[testenv:coverage-report]
base_python_file = .python-version
depends = coverage-combine
deps = coverage
skip_install = true
commands =
    coverage report
    coverage html


[testenv:lint]
skip_install = true
deps = prek
commands = prek run --all-files {posargs}


[testenv:typing-{mypy,pyright,ty,pyrefly}]
dependency_groups = tests
extras =
    prometheus
    sentry
    pool
    sqlalchemy
    sqlalchemy-asyncio
deps =
    mypy: mypy
    pyright: pyright
    ty: ty
    pyrefly: pyrefly
commands =
    mypy: mypy src
    pyright: pyright src
    ty: ty check
    pyrefly: pyrefly check


[testenv:docs-doctests]
base_python_file = .python-version
dependency_groups = tests
extras =
    pool
    sqlalchemy-asyncio
    prometheus
    sentry
commands =
    pytest README.md
